In [1]:
import numpy as np

# The Basics

In [2]:
a=np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b=np.array([[2,5,6,7],[2,4,5,6]])
print(b)

[[2 5 6 7]
 [2 4 5 6]]


In [4]:
c= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
#Get Dimension
c.ndim

3

In [6]:
# Get Shape
b.shape

(2, 4)

In [7]:
# Get Type
a.dtype

dtype('int16')

In [8]:
# Get Size
a.itemsize

2

In [9]:
# Get Total Size
a.nbytes

6