<a href="https://colab.research.google.com/github/sairatabassum/Numpy/blob/main/Numpy-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# The Basics

In [3]:
a=np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [4]:
b=np.array([[2,5,6,7],[2,4,5,6]])
print(b)

[[2 5 6 7]
 [2 4 5 6]]


In [5]:
c= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#Get Dimension
c.ndim

3

In [7]:
# Get Shape
b.shape

(2, 4)

In [8]:
# Get Type
a.dtype

dtype('int16')

In [9]:
# Get Size
a.itemsize

2

In [10]:
# Get Total Size
b.nbytes

64