# Accessing specific elements, rows, columns

In [1]:
import numpy as np
a= np.array([[1,2,3,4,5,6],[2,3,4,1,7,8]])
a

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 1, 7, 8]])

In [2]:
# Get a specific element
# a[0][2]
a[0,2]

3

In [3]:
# Get a specific element form last
a[0,-3]

4

In [4]:
# Get a specific row
a[1, :]

array([2, 3, 4, 1, 7, 8])

In [5]:
# Get a specific column
a[:,3]

array([4, 1])

In [6]:
# [start index:endindex:stepsize]
a[0, 1:6:3]

array([2, 5])

In [7]:
# Change value
a[1,3]=0
a[:,2]=1
a

array([[1, 2, 1, 4, 5, 6],
       [2, 3, 1, 0, 7, 8]])

## 3-d example

In [8]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# Get specific element
b[1,1,1]

8

In [10]:
# Change value
b[1,1,1]=0
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 0]]])

In [12]:
# Replace
b[0:,1,:]


array([[3, 4],
       [7, 0]])