<a href="https://colab.research.google.com/github/sairatabassum/Numpy/blob/main/Numpy-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Accessing specific elements, rows, columns

In [1]:
import numpy as np
a= np.array([[1,2,3,4,5,6],[2,3,4,1,7,8]])
a

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 1, 7, 8]])

In [16]:
# STart 0 end before 2
a[0:2]

array([[1, 2, 1, 4, 5, 6],
       [2, 3, 1, 0, 7, 8]])

In [3]:
# Get a specific element
# a[0][2]
a[0,2]

3

In [4]:
# Get a specific element form last
a[0,-3]

4

In [5]:
# Get a specific row
a[1, :]

array([2, 3, 4, 1, 7, 8])

In [6]:
# Get a specific column
a[:,3]

array([4, 1])

In [7]:
# [start index:endindex:stepsize]
a[1,1:6:3]


array([3, 7])

In [8]:
# Change value
a[1,3]=0
a[:,2]=1
a

array([[1, 2, 1, 4, 5, 6],
       [2, 3, 1, 0, 7, 8]])

## 3-d example

In [9]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# Get specific element
b[1,1,1]

8

In [11]:
# Change value
b[1,1,1]=0
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 0]]])

In [12]:
# Replace
b[0:,1,:]


array([[3, 4],
       [7, 0]])